name: notify
on:
  pull_request:
    branches:
      - master

jobs:
  notify:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
      - name: 'Send Notification'
        run: |
          jq -n ${{
            format('{
              attachments: [{
                pretext: "Swagger が更新されたよ！",
                color: "good",
                title: {0},
                title_link: {1}
            }', github.event.pull_request.title, github.event.pull_request.html_url)
          }} | curl -H 'Content-Type: application/json' -d @- ${{ secrets.SLACK_WEBHOOK }}
